from DeepSeaScavenger.wrappers.clip_reward import ClipReward
from DeepSeaScavenger.wrappers.discrete_actions import DiscreteActions
from DeepSeaScavenger.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from DeepSeaScavenger.wrappers.relative_position import RelativePosition
